### ISSUE TITLE
Look into sharing storage buffers 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#126]
When for example the colors are the same across millions of points.

**Comment by kushalkolar** [comment]
We could allow setting features like colors from a shared buffer, make some kind of `SharedBuffer` class which can be passed to colors for `LineGraphic`, `ScatterGraphic` etc. In these cases we should decide if we still want to allow slicable setting of `ColorFeature`, maybe we could and just print a warning that a `SharedBuffer` is being sliced and set since this will effects all `Graphic` objects that share the buffer.

**Comment by kushalkolar** [comment]
This might be possible by passing `color` to `LineMaterial` etc. instead of `colors` to `Geometry` when creating lines, scatters, etc. Need to thoroughly test VRAM usage when creating tens of thousands of lines.

**Comment by ArjunPutcha** [comment]
To confirm:
Goal is to create a class that can be called to store data - like colors - into shared memory objects. Upon initialization of the shared mem object, any Graphic objects linked to it will have to share R/W access to it (we can use mutexes). 

Then, each graphic object will called the sharedbuffer class instead of ColorFeature to initialize/read color array.

Is this still the goal?

**Comment by kushalkolar** [comment]
Nope, look into the uniform buffers in pygfx. They can be used for lines by setting the color on the LineMaterial instead of the Geometry.
