### ISSUE TITLE
Create a Proxy subclass that we use for our Graphic classes

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#161]
the purpose of this is having useful `__repr__` etc.

**Comment by clewis7** [comment]
just to clarify....

currently adding a graphic to a plot returns a `__repr__` that looks like this:

```<weakproxy at 0x7f28437e11d0 to ImageGraphic at 0x7f27f87d4610>```

but we want to return `__repr__` as they were before? 

```ImageGraphic @ 0x7fbb681a1360```

**Comment by kushalkolar** [comment]
yup, along with name etc.

I just noticed that the real repr prints if you check a `Plot` or `Subplot` so this is actually not too important for now. If it takes > 30 mins to figure out let's skip this for now.

**Comment by clewis7** [comment]
yes, and if you call `__repr__` on the proxy object that gets returned it will also give the correct `__repr__` for a graphic

**Comment by kushalkolar** [comment]
> so maybe just overriding the `__repr__` method for the proxy so that it actually returns the `__repr__` of what the proxy is pointing to as opposed to the current `__repr__` it returns?

if it's that simple, but I don't know

**Comment by almarklein** [comment]
I briefly looked at this. I initially thought that the proxy was a custom object, but it's a `weakref.proxy` object, which is builtin and cannot be subclassed. So basically there's no way to change the repr. You technically can implement your own custom varianf of `weakref.proxy` ... but that's probably a rabbit-hole.

An alternative solution is that the `Graphics` object becomes the proxy. That makes sense, I think, because it already plays the role of a proxy, projection fpl features onto pygfx world objects. In terms of code, this'd mean that the graphics instance holds a weakref (`weakref.ref()` or `weakref.proxy()`) to the `WorldObject` ... and that should be about it.

**Comment by kushalkolar** [comment]
Thanks for looking into it! 

Each `Graphic` uses a [weakref](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/graphics/_base.py#L100-L107) to the `pygfx.WorldObject`, however this was not sufficient for complete garbage collection. Since we have the various `GraphicFeatures` that wrap `pygfx.Buffer` (ex. [ColorFeature](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/graphics/_features/_colors.py#L20)) , and these can also hold event handlers of other graphics, it was necessary to have `Graphic` as a weakref as well to ensure both VRAM and system RAM get freed. This specifically traces back to this commit: https://github.com/fastplotlib/fastplotlib/pull/160/commits/5e9f5446aa4465b4cb615a59390be2edd12d5c9d#diff-87b8787e6cc96514902d278266d644006041f56cb59a1c3487193f564ea71afdL130-R150 

Since the repr is typically useful in ipython or notebooks I think we'll just implement #428 for now.
