### ISSUE TITLE
consider cmap library?

### ISSUE THREAD

**Issue by tlambert03** [fastplotlib/fastplotlib#387]
Hey @kushalkolar et al,

great package!  i was just looking around the image utils here and noticed that you [require matplotlib](https://github.com/fastplotlib/fastplotlib/blob/2873a677462551f47881e4c6dad637165f5230f6/fastplotlib/utils/generate_colormaps.py#L2) to generate colormaps but, understandably, [don't include matplotlib in your dependencies](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/utils/functions.py#L57C1-L58).

when working on napari and other related image libs, I also wanted to use colormaps without having to depend on matplotlib, and made [cmap](https://cmap-docs.readthedocs.io/en/latest/), a lib that only depends on numpy and provides all the matplotlib colormaps (and [many more](https://cmap-docs.readthedocs.io/en/latest/catalog/)) and basic mapping functionality.  the lib exports to many [third-party colormap objects](https://cmap-docs.readthedocs.io/en/latest/colormaps/#usage-with-external-visualization-libraries).  Would you be interested in looking at a PR that uses cmap here?

**Comment by kushalkolar** [comment]
Hi @tlambert03 I like this idea, thanks for posting! :smile: 

I really like this feature which seems like it lets you make custom arbitrary cmaps?

```python
In [2]: cmap1 = cmap.Colormap(["red", "green", "blue"])

In [3]: cmap1(np.linspace(0,1,5))
Out[3]:
array([[1.        , 0.        , 0.        , 1.        ],
       [0.50393701, 0.24900417, 0.        , 1.        ],
       [0.        , 0.50196078, 0.        , 1.        ],
       [0.        , 0.24900417, 0.50393701, 1.        ],
       [0.        , 0.        , 1.        , 1.        ]])
```

It would make it possible to have things like this in fastplotlib:

```python
# already exists
line.cmap = "jet"

# with your cmap lib :D 
line.cmap = ["red", "blue", "violet"]

# would apply to line collections as well
line_collection.cmap = ["red", "blue", "violet"]
```

For lines and scatter we use [`CmapFeature`](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/graphics/_features/_colors.py#L242)

For images we use [`ImageCmapFeature`](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/graphics/_features/_colors.py#L303)

In `fastplotlib` "Graphic Feature" classes are used to manage the buffers that represent various aspects of a graphic/plot item (such as the underlying data, colors, cmaps, etc.).

For LineCollection it's implemented within the Graphic class itself, in the [constructor](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/graphics/line_collection.py#L116-L117) and [cmap.setter](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/graphics/line_collection.py#L223-L226) .

I _think_ that for lines, scatter and line collections it should be possible to just use your `cmap` package in [`utils.functions.parse_cmap_values()`](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/utils/functions.py#L240-L305)

And also replace [`get_cmap()`](https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/utils/functions.py#L28-L63)

And have an updated list of qualitative cmaps because they behave differently: https://github.com/fastplotlib/fastplotlib/blob/main/fastplotlib/utils/functions.py#L12-L25

There might be other things in `utils.functions` that can be replaced with your `cmap` library, or other places as well! :)

**Comment by kushalkolar** [comment]
done in #390
